### ISSUE TITLE
editorskit/underline - Spotted this in the console

### ISSUE THREAD

**Issue by AlchemyUnited** [phpbits/block-options#100]
Format "editorskit/underline" is already registered to handle bare tag name "span". rich-text.min.js?ver=3.2.3:1 

Version 1.11

**Comment by phpbits** [comment]
@AlchemyUnited These errors are just notices and won't cause any issues on the editor. I've asked about this one to Gutenberg devs before and I believe they are working on the fixes : https://github.com/WordPress/gutenberg/pull/15072. Thanks!
