### ISSUE TITLE
EK conflict with my custom blocks

### ISSUE THREAD

**Issue by AlchemyUnited** [phpbits/block-options#101]
My blocks work fine, on their own as well as with other block libraries activated. But when I activate EK I get:

The editor has encountered an unexpected error...

And this in the console:

TypeError: this.activateMode is not a function
    at http://wprct.dev.cc/wp-includes/js/media-views.min.js?ver=5.2.2:1:24813
    at arrayEach (webpack-internal:///100:516:11)
    at Function.forEach (webpack-internal:///100:9344:14)
    at N.d._createModes (http://wprct.dev.cc/wp-includes/js/media-views.min.js?ver=5.2.2:1:24773)
    at N.d.initialize (http://wprct.dev.cc/wp-includes/js/media-views.min.js?ver=5.2.2:1:24182)
    at N.d.initialize (http://wprct.dev.cc/wp-includes/js/media-views.min.js?ver=5.2.2:1:25820)
    at N.d.initialize (http://wprct.dev.cc/wp-includes/js/media-views.min.js?ver=5.2.2:1:28692)
    at N.d.b.View (http://wprct.dev.cc/wp-includes/js/backbone.min.js?ver=1.2.3:1:14137)
    at N.d.constructor (http://wprct.dev.cc/wp-includes/js/wp-backbone.min.js?ver=5.2.2:1:2616)
    at N.d.constructor (http://wprct.dev.cc/wp-includes/js/media-views.min.js?ver=5.2.2:1:23629)

I presume it's something I've done (wrong), but I have no clue where to start on trying to figure out what went wrong. Any chance you can spare a couple minutes and perhaps give me some direction on trying to sort this out? tia

p.s. Oddly enough, I get an error even when trying to add a new page. That is, there are no blocks added to the page.

**Comment by AlchemyUnited** [comment]
Not sure if this helps but it seems that the problem is only admin / editor side. Things display fine and as expected on the front end - with both plugins activated. 

In fact, I deactivated my blocks. Then highlighted some text with EK. Saved. Went to the frontend and refreshed. Saw the highlighted text. 

Then I reactivated my blocks. My blocks and the highlight text were fine on the frontend. Tho' there was still the error screen on the backend :(

**Comment by AlchemyUnited** [comment]
p.s. I deactivated EK and the highlighting was still there. I understand why the span needs to stay, but I'm not so sure the background-color for the style should be inlined in the span. I would think the span could have a class, and that class could define the color. 

1) This allows the hightlighting to be "removed".

2) This allows me / someone to change the highlight color if they want. 

I don't want to get on my soapbox - again? :) - but this inline'ing of styles is creating "forward compatability" issues that could possibly lead to plenty of tears (and swearing) at some point in the future. The sooner we all stop doing this, the better.  imho, of course ;)

**Comment by phpbits** [comment]
@AlchemyUnited Would you mind sending me the link of your custom block? I've tested EditorsKit with other blocks plugin and it's working perfectly. Did the error disappears after you deactivated EditorsKit? You might also want to check your Reusable Blocks, I have the same error before and turns out related to old Reusable Blocks. It seems that Reusable Blocks are also loaded when the editor is loaded. Let me know how it goes. Thanks!

**Comment by AlchemyUnited** [comment]
Let me do some more reworking of my webpack stuff to see if that helps. I'll get back to you if I'm still running into problems. Someone did point me to this, but that didnt' seem to help, at least not on first try. Thanks again. 

https://wpdevelopment.courses/how-to-fix-activatemode-is-not-a-function-error-in-gutenberg/
