### ISSUE TITLE
download form probably do not work

### ISSUE THREAD

**Issue by tkapler** [phpbits/block-options#150]
sorry for using this form but your forms on https://editorskit.com/ probably do not work - any email i put it and it does nothing. Not a big issue as it can be downloaded from wp plugins, but anyway.

BTW: is there some any way, how you can add &nbsp; in Gutenberg editor? If not - could you please add this option to your excelent plugin?

**Comment by phpbits** [comment]
@tkapler Just tested and seems to be working fine. I'll try to replicate the issue that you are having.

Would you mind elaborating your suggestion and will be very happy to check it I can add that on the plugin. Thanks a lot!

**Comment by tkapler** [comment]
I have just checked it again and still do nothing, tested in Chrome /
Firefox (windows), at least from the point of visitor - if you go to
https://editorskit.com/, type any email the input, click Download - the
input just changes its background and thats it. No message, no info for
user. So maybe it works (i see it network panel, that the post request is
sent), but it seems it does nothing.
Tomáš Kapler
