### ISSUE TITLE
Add Special Characters Inserter Format

### ISSUE THREAD

**Issue by phpbits** [phpbits/block-options#167]
TinyMCE reference : https://www.tiny.cloud/docs/plugins/charmap/

**Comment by icc365** [comment]
I second this request as I use this feature on the Classic editor in WP. I'm one person who would use the block editor more if it had insertable characters because I do use them a lot in content.

**Comment by FriendlyWP** [comment]
Yes, please! I know 10up has released a free plugin that does this but it would be great to have it all wrapped up within one plugin since I already have EditorsKit installed. :) Thanks Jeffrey!

**Comment by phpbits** [comment]
@FriendlyWP @icc365 I'm working on this one and it will be available on the next release :) Here's the preview.

![Gutenberg Special Characters Inserter Format](https://user-images.githubusercontent.com/3365507/75267046-32aa8f80-582e-11ea-841b-0841f7523455.gif)

**Comment by phpbits** [comment]
@FriendlyWP @icc365 You can now get this functionality on the latest EditorsKit version :)

**Comment by arielestigarribia** [comment]
Hi Jeffrey @phpbits, Amazing Job!! 
When it's going to be available this feature for drupal-gutenberg EditorsKit?
Best Regards!
