### ISSUE TITLE
Manage EditorsKit Features

### ISSUE THREAD

**Issue by phpbits** [phpbits/block-options#17]
Create navigation option to enable/disable editorskit features.

**Comment by phpbits** [comment]
Preview:

![Manage EditorsKit Features](https://user-images.githubusercontent.com/3365507/58081791-3dbdf880-7be8-11e9-95cf-9810e19bc245.gif)

**Comment by AlchemyUnited** [comment]
fwiw, this is related to this

https://github.com/phpbits/block-options/issues/23

p.s. I would move the manage features outside the main UI / UX. That is. 

1) It could / should be role dependent. That is, I ("the boss") would want to "configure" EK for the staff. I don't want them making up their own set of setting.

2) The GB UI / UX is already in need of a makeover. Sooner or later it's gonna have to be refactored. (Yeah, probably later but none the less.) If the settings were external you're safer. Also, I think it might be easier to export / import setting if you're outside frontend-y GB. 

imho, of course ;)

**Comment by phpbits** [comment]
@AlchemyUnited Thank you very much for your suggestions! I'll definitely create separate plugin settings on the future to manage user roles that will have access to EditorsKit Settings panel. As of the moment, I just don't want users to leave the editor to manage the features.

**Comment by phpbits** [comment]
And also, JS actions are required to disable editors features. It's easier and better to do this directly on the editor. I hope this makes sense. Thanks!
