### ISSUE TITLE
Underline Rich Text format is missing 

### ISSUE THREAD

**Issue by elvismdev** [phpbits/block-options#195]
I cannot see the option to enable/disable the Underline format text option, it does't display from block editors as well.

Might this be related? https://github.com/phpbits/block-options/commit/5fd525d9fa73b03f95d1aa78d6ef703f0433f119

**Comment by phpbits** [comment]
@elvismdev I removed the underline format because it's already exists on Gutenberg core. Though it's not visible you can press CTRL or CMD + U. Thanks!

**Comment by elvismdev** [comment]
> @elvismdev I removed the underline format because it's already exists on Gutenberg core. Though it's not visible you can press CTRL or CMD + U. Thanks!

We'll yeah we know that. Similar how you can do bold and italics with kb commands, but still a UI exists for them since there are some users that will expect/prefer to click a button. 

Now I am confused I thought that was the purpose of this plugin ╮(. ❛ ᴗ ❛.)╭

**Comment by phpbits** [comment]
@elvismdev I've added this because it's not available before but it's causing JS error and I have to take this feature out. I'll try to add it back w/o causing any issue but for the meantime you can use the shortcut. Thanks!
