### ISSUE TITLE
Settings page completely blank

### ISSUE THREAD

**Issue by small-fork** [phpbits/block-options#208]
Hello,

The settings page for Editorskit is not displaying anymore, so I'm unable to access the settings at all. I've updated to the most recent version of the plugin, but it still is blank. I'm also running the most recent Wordpress version (5.3.1).

I'm attaching a screenshot of the blank settings page. It also adds odd spacing at the top of the sidebar and obscures part of a notice.

Please let me know if there is additional information I should provide. Thank you!

![editorskit-setting-behavior](https://user-images.githubusercontent.com/27249070/71225400-2a6a2d00-229e-11ea-9ea0-b9d33d8068ec.jpg)

**Comment by phpbits** [comment]
@small-fork Thanks a lot for reporting this issue. Would you mind sending screenshot of the console log as well? There might be a plugin conflict and would be really happy to fix it.

**Comment by small-fork** [comment]
@phpbits Thank you for the prompt reply! I hope this is what you were wanting, but if not, just let me know:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/27249070/71268806-6a1f2c00-2313-11ea-824a-d0ea1df4c6f4.png">

**Comment by phpbits** [comment]
@small-fork My apology for late response. It seems that the error is coming from lifterlms-blocks. Would you mind letting me know the plugin link? Thanks!

**Comment by small-fork** [comment]
@phpbits No worries! That's the Lifter LMS ecourse plugin. I also have several of their supporting plugins.

[This is their site](https://lifterlms.com/)

I also have these installed: 
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/27249070/71559476-10f67d00-2a24-11ea-95a5-e65961c1a3fe.png">

I think the details for all of them are [here](https://lifterlms.com/store/).

Let me know if there's anything else you need and thank you!

**Comment by phpbits** [comment]
@small-fork Seems like it's a premium plugin. Would you mind sending me a copy at jeffrey.carandang8 at gmail dot com? Thanks!

**Comment by small-fork** [comment]
Apologies for my ignorance, @phpbits but do you mean the original .zip file of the main Lifter LMS plugin? If so, I need to get it from the developer who set up the staging site as I think they have the original .zip. But wanted to be sure I'm understanding you correctly :) Thank you!

**Comment by phpbits** [comment]
@small-fork Yes, I need the plugin file to test the issue locally. Thanks!

**Comment by small-fork** [comment]
@phpbits Sorry for continued confusion—the core Lifter plugin is actually free. It's only the add-ons that are premium. Is one of the add-ons the issue? 

Here is the page for the core plugin: https://wordpress.org/plugins/lifterlms/ 

If you're needing one of the add-ons, please let me know and I can ask the developers for the file. The add-ons I have installed are in the screenshot a few comments up.

Thank you!

**Comment by phpbits** [comment]
Thanks a lot @small-fork! I've managed to pinpoint the issue. Could you add this to your changes to your copy for the meantime : https://github.com/phpbits/block-options/pull/216/files. Just add the lines on 98 and 99. Let me know how it goes. Thanks!

**Comment by small-fork** [comment]
@phpbits Thank you for the reply! Just to clarify, where do I put that code? Apologies for the confusion!

**Comment by phpbits** [comment]
@small-fork You can just update to the latest version :) I've uploaded the fixes. Thanks!
