### ISSUE TITLE
When activating multiple plugins, block-options / editor's kit kills the process. 

### ISSUE THREAD

**Issue by bobbytechhaus** [phpbits/block-options#209]
I was trying to install several plugins at once today from wp cli, and the process stopped when it got tp this:
 
`Warning: Some code is trying to do a URL redirect. Backtrace:
#0  WP_CLI\Utils\wp_redirect_handler(http://blogswp.test/wp-admin/options-general.php?page=editorskit-getting-started) called at [/var/www/html/wp-includes/class-wp-hook.php:290]
#1  WP_Hook->apply_filters(http://blogswp.test/wp-admin/options-general.php?page=editorskit-getting-started, Array ([0] => http://blogswp.test/wp-admin/options-general.php?page=editorskit-getting-started,[1] => 302)) called at [/var/www/html/wp-includes/plugin.php:206]
#2  apply_filters(wp_redirect, http://blogswp.test/wp-admin/options-general.php?page=editorskit-getting-started, 302) called at [/var/www/html/wp-includes/pluggable.php:1230]
#3  wp_redirect(http://blogswp.test/wp-admin/options-general.php?page=editorskit-getting-started, 302, WordPress) called at [/var/www/html/wp-includes/pluggable.php:1373]
#4  wp_safe_redirect(http://blogswp.test/wp-admin/options-general.php?page=editorskit-getting-started) called at [/var/www/html/wp-content/plugins/block-options/includes/class-editorskit-welcome.php:148]
#5  EditorsKit_Welcome->redirect(block-options/plugin.php, ) called at [/var/www/html/wp-includes/class-wp-hook.php:288]
#6  WP_Hook->apply_filters(, Array ([0] => block-options/plugin.php,[1] => )) called at [/var/www/html/wp-includes/class-wp-hook.php:312]
#7  WP_Hook->do_action(Array ([0] => block-options/plugin.php,[1] => )) called at [/var/www/html/wp-includes/plugin.php:478]
#8  do_action(activated_plugin, block-options/plugin.php, ) called at [/var/www/html/wp-admin/includes/plugin.php:708]
#9  activate_plugin(block-options/plugin.php, , ) called at [phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php:323]
#10 Plugin_Command->activate(Array ([0] => gutenberg,[1] => codepress-admin-columns,[2] => dropit,[3] => block-options,[4] => jetpack,[5] => svg-support,[6] => wpforms-lite), Array ())
#11 call_user_func(Array ([0] => Plugin_Command Object ([*item_type] => plugin,[*upgrade_refresh] => wp_update_plugins,[*upgrade_transient] => update_plugins,[*obj_fields] => Array ([0] => name,[1] => status,[2] => update,[3] => version),[*chained_command] => ,[WP_CLI\CommandWithUpgrademap] => Array ([short] => Array ([inactive] => I,[active] => A,[active-network] => N,[must-use] => M,[parent] => P,[dropin] => D),[long] => Array ([inactive] => Inactive,[active] => Active,[active-network] => Network Active,[must-use] => Must Use,[parent] => Parent,[dropin] => Drop-In)),[fetcher] => WP_CLI\Fetchers\Plugin Object ([*msg] => The '%s' plugin could not be found.)),[1] => activate), Array ([0] => gutenberg,[1] => codepress-admin-columns,[2] => dropit,[3] => block-options,[4] => jetpack,[5] => svg-support,[6] => wpforms-lite), Array ()) called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:98]
#12 WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array ([0] => gutenberg,[1] => codepress-admin-columns,[2] => dropit,[3] => block-options,[4] => jetpack,[5] => svg-support,[6] => wpforms-lite), Array ())
#13 call_user_func(Closure Object (), Array ([0] => gutenberg,[1] => codepress-admin-columns,[2] => dropit,[3] => block-options,[4] => jetpack,[5] => svg-support,[6] => wpforms-lite), Array ()) called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:451]
#14 WP_CLI\Dispatcher\Subcommand->invoke(Array ([0] => gutenberg,[1] => codepress-admin-columns,[2] => dropit,[3] => block-options,[4] => jetpack,[5] => svg-support,[6] => wpforms-lite), Array (), Array ()) called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:371]
#15 WP_CLI\Runner->run_command(Array ([0] => plugin,[1] => activate,[2] => gutenberg,[3] => codepress-admin-columns,[4] => dropit,[5] => block-options,[6] => jetpack,[7] => svg-support,[8] => wpforms-lite), Array ()) called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:394]
#16 WP_CLI\Runner->run_command_and_exit() called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1160]
#17 WP_CLI\Runner->start() called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:23]
#18 WP_CLI\Bootstrap\LaunchRunner->process(WP_CLI\Bootstrap\BootstrapState Object ([WP_CLI\Bootstrap\BootstrapStatestate] => Array ())) called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:74]
#19 WP_CLI\bootstrap() called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27]
#20 include(phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php) called at [phar:///usr/local/bin/wp/php/boot-phar.php:11]
#21 include(phar:///usr/local/bin/wp/php/boot-phar.php) called at [/usr/local/bin/wp:4]
`

On another site, I went to activate a bunch of plugins from the wordpress backend by clicking the checkmarks and Bulk Action -> Activate, and it seems the process of activation stopped at the same spot.

**Comment by phpbits** [comment]
@bobbytechhaus Thanks a lot for reporting this issue. I'll exclude WP CLI activation to welcome page redirect in the next update. :)
