### ISSUE TITLE
[Question] How to remove stylesheets?

### ISSUE THREAD

**Issue by lonix1** [phpbits/block-options#219]
I sometimes need to remove the plugin's css (without removing the plugin itself).

For example, this is how I remove block stylesheets (but still keep block support):
````php
add_action('wp_print_styles', function() {
  wp_dequeue_style('wp-block-library');
}, 100);
````

Can I do something similar for this plugin's stylesheets?

**Comment by phpbits** [comment]
@lonix1 You can use this code to disable the loading of EditorsKit frontend stylesheet :

```
function editorskit_dequeue_script() {
    wp_dequeue_script( 'editorskit-frontend' );
}
add_action( 'wp_print_scripts', 'editorskit_dequeue_script', 100 );
```

Let me know how it goes. Thanks!

**Comment by lonix1** [comment]
I assume this removes the js... will it also remove the css?

**Comment by phpbits** [comment]
@lonix1 Sorry. I've updated the code to use style instead of scripts. Thanks!

**Comment by lonix1** [comment]
Actually maybe you were right the first time.

I just learnt that the "old" way is `wp_print_styles` and `wp_print_scripts`, but for recent wordpress, the "better" hook (less bugs apparently) is `wp_enqueue_scripts` - and it covers both css and js!

Thanks for your help!

**Comment by lonix1** [comment]
Lol, you were right the first AND second times! 😆 

It's important to use `wp_enqueue_scripts`, but it's also important to use `wp_dequeue_style` (because the plugin only adds styles).

Thanks again!
