### ISSUE TITLE
Hiding page titles removes them from Yoast WordPress SEO breadcrumbs

### ISSUE THREAD

**Issue by FriendlyWP** [phpbits/block-options#222]
I'm not sure how Yoast is pulling the current page title for breadcrumbs, but it's conflicting with the way EditorsKit removes page titles. If "Hide Page Title" is checked, it not only removes it as a page title, it removes the final piece (the current page title) from the breadcrumbs. It's actually removed, not just hidden.

Any way to fix this would be much appreciated! Thanks!

**Comment by phpbits** [comment]
@FriendlyWP Thanks a lot for reporting this issue. I'll take a look and will let you know once I have concrete solution. Thanks again!
