### ISSUE TITLE
EditorsKit 1.24 breaks Gravity Forms blocks previews in admin

### ISSUE THREAD

**Issue by FriendlyWP** [phpbits/block-options#228]
The latest version of EditorsKit (1.24) breaks Gravity Forms block in the editor (but not the front-end); Any Gravity Form block in the editor just shows a gray block with the error `Error loading block: Invalid parameter(s): attributes`.  If I disable EditorsKit it shows the form itself in the editor again.

I'm running WP 5.3.2 and also have installed Gutenberg 7.3.0.

**Comment by phpbits** [comment]
@FriendlyWP I'll look into this issue and will let you know how it goes. Thanks!

**Comment by phpbits** [comment]
@FriendlyWP Found the issue :) Could you replace `includes/class-editorskit-post-meta.php` with this one and let me know if it's working perfectly on your end as well : https://github.com/phpbits/block-options/blob/fix/block-preview-issue/includes/class-editorskit-post-meta.php

Thanks a lot!

**Comment by phpbits** [comment]
@FriendlyWP  Uploaded the fixes on the latest version. Let me know if in any case you encounter any other issues. Thanks!
