### ISSUE TITLE
"Media & Text" Blocks Broken in Non-Chrome Browsers

### ISSUE THREAD

**Issue by rjscully** [phpbits/block-options#229]
The following message appears when editing page content blocks in various circumstances using browsers other than Chrome:
"This block has encountered an error and cannot be previewed."

All browsers tested using EditorsKit 1.24 and WordPress 5.3.2. Everything works as-expected with Chrome 79.0.3945.130 but not with other browsers.

**Firefox 72.0.2**
1. Edit a page in the admin area
2. Add a "Media & Text" content block
3. Add an image to the block (upload or media library)
4. Click the "Media Link" button on the block's toolbar
5. Begin typing any text, or paste a link

**Expected:** Text to appear in link field
**Result:** Block contents disappear and "This block has encountered an error and cannot be previewed." text is displayed in place of contents. NS_ERROR_ILLEGAL_VALUE exception thrown in console.

**Edge 44.18362.449.0 Use Case 1**
1. Edit a page in the admin area
2. Add a "Media & Text" content block
3. Add an image to the block (upload or media library)

**Expected:** Image to appear in Media & Text Block
**Result:** Block contents disappear and "This block has encountered an error and cannot be previewed." text is displayed in place of contents. 

**Edge 44.18362.449.0 Use Case 2**
1. In the admin area, edit a page which already has a Media & Text block with an image in the block
2. Click the Media & Text block anywhere except in the text/"Content..." section

**Expected:** The block to become the active element and show the toolbar
**Result:** Block contents disappear and "This block has encountered an error and cannot be previewed." text is displayed in place of contents.

**Comment by phpbits** [comment]
@rjscully Thanks a lot for reporting this issue. Could you replace includes/class-editorskit-post-meta.php with this one and let me know if it's working perfectly on your end as well : https://github.com/phpbits/block-options/blob/fix/block-preview-issue/includes/class-editorskit-post-meta.php

Thanks a again!

**Comment by phpbits** [comment]
Hi rjscully ,

Are you using Gutenberg plugin as well? The latest plugin version added the Media & Text Block link option. This issue will be fixed by deactivating the same features that are already available on EditorsKit. Please follow this guide and let me know how it goes. Thanks a lot!

https://phpbits.d.pr/wILkwN

**Comment by rjscully** [comment]
Thanks for your reply. I am not using Gutenberg, but had tried with Gutenberg installed before submitting this issue.

I applied the code change with this result (new compared versus old **class-editorskit-post-meta.php**):
```
/var/www/html/wp-content/plugins/block-options/includes# diff class-editorskit-post-meta.php class-editorskit-post-meta.php.old
81,87d80
<
<                       if ( isset( $request['attributes'] ) && isset( $request['attributes']['hasAlignmentOption'] ) ) {
<
<                               $attributes = $request['attributes'];
<                               unset( $attributes['hasAlignmentOption'] );
<                               $request['attributes'] = $attributes;
<  
```

With the above code change, the problem is still happening in Firefox and Edge.

After that change, I went and followed the guide for disabling "Media Text Block Link" in EditorsKit features manager, but that just removed the link from the "Media Link" button from the toolbar entirely (disabled the feature). The link feature is very useful but not presently working, so I don't want to disable it. Re-installing Gutenberg did not cause the "Media Link" button on the toolbar to reappear, so I reversed the steps in the guide and it reappeared.

Let me know if it seems like I did anything improperly or overlooked any instructions.

**Comment by rjscully** [comment]
The tl;dr is that there is no problem with your project. This issue can be closed with no commit.

Incidentally, I tried to buy you a coffee and it says you need to setup a payment method: "Payments are disabled until the creator has selected a payment method. Please contact the creator." Consider adding a "Support" section to the readme to make your choice method of support easy for appreciative users to find!

In any case, thanks for your work and help as I worked through the problem (it was related to Gutenberg but quite a mess to explain).

**Comment by phpbits** [comment]
@rjscully  You are very welcome. I'll be disabling the EditorsKit media text block link whenever the Gutenberg plugin version is the same with the one in core WordPress. Thanks a lot!
