### ISSUE TITLE
Suggestion/Request: Heading Block Font Sizes

### ISSUE THREAD

**Issue by prosvitco** [phpbits/block-options#232]
Was wondering if it was possible to add font size settings to the heading block ( just like what you did for the lists ).  Sometimes designs do not follow style guides and headings need to be different, this would resolve it? 

Thank you!

**Comment by phpbits** [comment]
@prosvitco Thanks a lot for the suggestion. The typography add-on for Gutenberg is currently on private beta : https://editorskit.com/wordpress-gutenberg-editor-typography-and-google-fonts-add-on/ . You can test it out for font sizes and typography handling. Use `BETATEST` coupon code for discount. I hope this could help on the features you are looking for. Thank again!
