### ISSUE TITLE
Custom Hightlight Color change Bug

### ISSUE THREAD

**Issue by towfiqi** [phpbits/block-options#256]
Hi,

Thanks for the awesome plugin.  Great work.

I found an issue while selecting custom highlight/text color. Try adding custom highlight color to text and you will notice that when you try to drag and move the colorpicker, the colopicker popup hides itself. 

I think something changed with the latest version of Gutenberg which is causing this issue.

**Comment by phpbits** [comment]
@towfiqi It's Gutenberg editor bug and they've fixed it on the plugin version. These fixes will be available on core WordPress on next release. Thanks!

**Comment by towfiqi** [comment]
Great! :)
