### ISSUE TITLE
Theme palette/colors missing

### ISSUE THREAD

**Issue by strarsis** [phpbits/block-options#270]
@phpbits: EditorsKit seems to add background color functionality to the `core/table` block which is great. However, the available colors are only default colors in EditorsKit plugin, not the one the theme added by itself. The theme uses `add_theme_support( 'editor-color-palette'` in `after_setup_theme` action.

**Comment by phpbits** [comment]
@strarsis Thank you for reporting this issue but Table background wasn't added by EditorsKit. This feature is available and added by core Gutenberg : https://github.com/WordPress/gutenberg/blob/55fed74a956734b043ef723254f02f19f9689037/packages/block-library/src/table/edit.js#L58. Thanks again!
