### ISSUE TITLE
Unable to edit blocks which are part of a reusable block

### ISSUE THREAD

**Issue by markhowellsmead** [phpbits/block-options#277]
When I create a reusable block from multiple other blocks, then edit the reusable block and click on a child block to edit it, the following two errors are thrown.

(The same issue occurs when the reusable block is just a simple paragraph.)

    TypeError: Cannot read property 'filter' of undefined
    TypeError: Cannot read property 'clientId' of undefined

**To reproduce**

- Add a core/heading and core/paragraph with some simple text
- Create a group from these two blocks
- Convert the group to a reusable block.
- Edit the reusable block.
- Click on e.g. the heading to edit it.

**Expected behavior**
The text should be editable.

**Editor version**
- WordPress version **5.4**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **Either**

**Desktop**
 - OS: **OSX**
 - Browser **Chrome**
 - Version **81**

**Comment by lubieowoce** [comment]
just tested, happens for me too. looks like it's a bug in `extensions/formats/indent-increase`. apparently when editing a reusable block, `getSelectedBlock()` returns `null` at some point, breaking stuff. unfortunately due to a logic bug in the "feature enabled" check, disabling the format doesn't help :(

**Comment by lubieowoce** [comment]
I've submitted a fix (https://github.com/phpbits/block-options/pull/278). you can manually copy the files into your `plugins/block-options` and give it a spin :) it fixed the issue for me.
