### ISSUE TITLE
Another suggestion: Clear all formatting

### ISSUE THREAD

**Issue by AlchemyUnited** [phpbits/block-options#35]
I was looking for a way to remove things from the More Rich Text Controls (ideally in some case, remove the entire select**) , came across this, and thought of EK

https://wordpress.stackexchange.com/questions/329212/remove-formatting-in-rich-text-with-gutenbergs-block-editor

** If you've come across a way to modify that select, or be able to remove it, please share. tia

**Comment by phpbits** [comment]
@AlchemyUnited  @deckerweb Here's how the clear formatting works. Being able to highlight and select specific text to remove formatting is the feature missing on Ella's Advanced Rich Text Tools. With this, clear formatting is working the same way as the old TinyMCE 💯
