### ISSUE TITLE
Plugin conflict with Thrive Comments plugin

### ISSUE THREAD

**Issue by deckerweb** [phpbits/block-options#49]
Sadly, there is a plugin conflict with "Thrive Comments" a premium plugin by "Thrive Themes".
As long as "EditorsKit" is active the comments won't be loaded anymore for logged-out users.
You would need to deactivate EditorsKit to have comments loading or deactivate Thrive Comments to keep using EditorsKit.

I just noticed on one of my live sites running Thrive Comments and EditorsKit 1.5

Since Thrive Comments is premium I can provide you with a copy for testing purposes. Let's connect on Slack for that ;-)

Thanks in advance!

**Comment by phpbits** [comment]
@deckerweb Fixed and added on version 1.6 which is available in a few. Thanks a lot for such huge help on fixing this issue!
