### ISSUE TITLE
Ability to define post/ page title selector for better hiding

### ISSUE THREAD

**Issue by BinaryMoon** [phpbits/block-options#74]
I like the title hiding feature - I think it could be really handy. However sometimes it leaves behind title containers such as the <header> element. These often come with margins and padding which then changes the position of the post content.

What I would like to see is something like `add_theme_support( 'editorskit-title' )` that requires a selector for the header container so I can ensure the wrapper gets hidden too.

Things I don't know:

* Should the add_theme_support be specific to the feature or the entire plugin?

**Comment by phpbits** [comment]
@BinaryMoon Thanks a lot for the suggestion. Working on it and I'm not sure how `add_theme_support` can fit it. For the meantime I can add body class `editorskit-title-hidden` so elements can easily be hidden via CSS. What do you think?

**Comment by BinaryMoon** [comment]
Hey @phpbits - that would be absolutely fine. Just as easy to add support that way.

Thanks! :)

**Comment by phpbits** [comment]
@BinaryMoon Added :) It's also easier to support for non-tech users. I'll just ask them to add custom CSS code into the customizer 👍
