### ISSUE TITLE
more specific classes in editorskit-frontend CSS

### ISSUE THREAD

**Issue by dabasti** [phpbits/block-options#79]
at the moment you are using classes like `.flex`, `.flex-row`, etc. These stay in conflict with some classes used in my own CSS. I would suggest using a prefix such as `.ek-` to avoid conflicts with other themes as .flex might be a common used class

**Comment by phpbits** [comment]
@dabasti  Thanks a lot for reporting this conflict. I've updated the classes on version 1.9.1. Let me know if you encounter any other issues or have any suggestions. Thanks again!
