### ISSUE TITLE
TypeError: Cannot read property 'desktop' of undefined

### ISSUE THREAD

**Issue by onuro** [phpbits/block-options#80]
Hey Man,

Great plugin. However it conflicts with mine, especially when my plugin tries to import a json block template data and place it into the editor.

The display extension can not read the template's non-existent attributes and throws an error, making the template unusable.

Here's a video of the issue: https://cl.ly/14c4230c8644

How do you think we can overcome this issue?

Thanks!

**Comment by phpbits** [comment]
@onuro Thanks a lot for reporting the issue. I've created the fixes and will be available on the next release. You can also check using this branch : https://github.com/phpbits/block-options/tree/compatibility/kioken-blocks . Thanks!

**Comment by onuro** [comment]
Brilliant thanks man!

**Comment by phpbits** [comment]
@onuro You are very welcome :) I'll add the fixes on the next release. I'll let you know when it's added on the .org repo.
